import { App } from '../vue/dist/vue.esm-bundler.js';

declare const BonkersUI: {
    install(app: App): void;
};
export default BonkersUI;
export { UiAlert, EAlertTypes } from './components/ui-alert';
export { UiBackdrop } from './components/ui-modal/ui-backdrop';
export { UiBadge, EBadgeKind, EBadgeSize } from './components/ui-badge';
export { UiBerRank, EBerSize } from './components/ui-ber-rank';
export { UiButton, EButtonSizes, EButtonTypes } from './components/ui-button';
export { UiCardCta } from './components/ui-card-cta';
export { UiCardResult } from './components/ui-card-result';
export { UiCardSimple } from './components/ui-card-simple';
export { UiCheckbox } from './components/ui-checkbox';
export { UiDropdown, EDropdownKinds } from './components/ui-dropdown';
export { UiIcon, ESize } from './components/ui-icon';
export { UiIconWrapper, EIconWrapperTypes, EIconWrapperSizes } from './components/ui-icon-wrapper';
export { UiInput, EInputType, EInputKinds, EAutocomplete } from './components/ui-input';
export { UiInputRange } from './components/ui-input-range';
export { UiListItem, EListItemTypes, EListItemSpacing, EListItemSize } from './components/ui-list-item';
export { UiMediaCard } from './components/ui-media-card';
export { UiModal, EModalSizes } from './components/ui-modal';
export { UiNotificationBadge, EBadgeOrigin } from './components/ui-notification-badge';
export { UiOrderCard } from './components/ui-order-card';
export { UiPlainRadio } from './components/ui-plain-radio';
export { UiProgress } from './components/ui-progress';
export { UiRadio } from './components/ui-radio';
export { UiRadioCompact } from './components/ui-radio-compact';
export { UiRadioFancy } from './components/ui-radio-fancy';
export { UiResultCardRange } from './components/ui-result-card-range';
export { UiRipple } from './components/ui-ripple';
export { UiSelect } from './components/ui-select';
export { UiSkeleton } from './components/ui-skeleton';
export { UiSnackbar, ESnackbarTypes } from './components/ui-snackbar';
export { UiTable, ETableKind, ERowKind } from './components/ui-table';
export { UiTableCell } from './components/ui-table/ui-table-cell';
export { UiTableRow } from './components/ui-table/ui-table-row';
export { UiTabs } from './components/ui-tabs';
export { UiToggle } from './components/ui-toggle';
export { UiTypography, EColors, ETypographySizes, ETextWeight, ETextAlign, ETextTransform } from './components/ui-typography';
export { UiVerificationInput } from './components/ui-verification-input';
//# sourceMappingURL=index.d.ts.map