name: Deploy beta
# site:
#   use_directory_urls: false
#   siteUrl: https://bonkers-ie.github.io/bonkers-ui/
#   site_url: https://bonkers-ie.github.io/bonkers-ui/
on:
  push:
    branches:
      - develop
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
            bun-version: latest
      - run: bun i
      - run: bun lint:script
      - run: bun lint:style
      - run: bun run test
      - run: bun build-storybook
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static
          cname: https://bonkers-ie.github.io/bonkers-ui/
