name: Linting
# site:
#   use_directory_urls: false
#   siteUrl: https://bonkers-ie.github.io/bonkers-ui/
#   site_url: https://bonkers-ie.github.io/bonkers-ui/
on:
  pull_request:
    branches:
      - develop
      - master
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
            bun-version: latest
      - run: bun i
      - run: bun lint:script
      - run: bun lint:style
      - run: bun test
